runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'sourcecodesql'
  MYSQL_DB: 'covid_tracker'
  MYSQL_HOST: '104.154.253.11'

handlers:

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles